name: before_after
description: A flutter package which makes it easier to display the difference between two images.
version: 2.0.1
author: Sahil Kumar <xdsahil@gmail.com>
homepage: https://github.com/xsahil03x/before_after

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
